// =========================================================================
// CAS Identities Truth Table
// =========================================================================
// Single source of truth for simplify rewrite identities.
// Each entry maps a one-way canonical rewrite with metadata:
//   - id: unique rule key
//   - priority: lower runs earlier
//   - lhs: AST pattern (supports wildcard nodes `(type: "wild", name: "...")`)
//   - rhs: AST template
//   - label: human-readable identity text
//   - domain-sensitive: metadata flag for domain-caveat identities
// =========================================================================

#import "../expr.typ": *

/// Public helper `identity-rules`.
#let identity-rules = (
  // Trig Pythagorean
  (
    id: "trig-pythagorean",
    priority: 10,
    lhs: add(pow(func("sin", (type: "wild", name: "u")), num(2)), pow(func("cos", (type: "wild", name: "u")), num(2))),
    rhs: num(1),
    label: "sin²(u) + cos²(u) = 1",
    domain-sensitive: false,
  ),
  // Reciprocal canonical forms
  (
    id: "recip-sin",
    priority: 20,
    lhs: cdiv(num(1), func("sin", (type: "wild", name: "u"))),
    rhs: func("csc", (type: "wild", name: "u")),
    label: "1/sin(u) = csc(u)",
    domain-sensitive: false,
  ),
  (
    id: "recip-cos",
    priority: 21,
    lhs: cdiv(num(1), func("cos", (type: "wild", name: "u"))),
    rhs: func("sec", (type: "wild", name: "u")),
    label: "1/cos(u) = sec(u)",
    domain-sensitive: false,
  ),
  (
    id: "recip-tan",
    priority: 22,
    lhs: cdiv(num(1), func("tan", (type: "wild", name: "u"))),
    rhs: func("cot", (type: "wild", name: "u")),
    label: "1/tan(u) = cot(u)",
    domain-sensitive: false,
  ),
  (
    id: "recip-sinh",
    priority: 23,
    lhs: cdiv(num(1), func("sinh", (type: "wild", name: "u"))),
    rhs: func("csch", (type: "wild", name: "u")),
    label: "1/sinh(u) = csch(u)",
    domain-sensitive: false,
  ),
  (
    id: "recip-cosh",
    priority: 24,
    lhs: cdiv(num(1), func("cosh", (type: "wild", name: "u"))),
    rhs: func("sech", (type: "wild", name: "u")),
    label: "1/cosh(u) = sech(u)",
    domain-sensitive: false,
  ),
  (
    id: "recip-tanh",
    priority: 25,
    lhs: cdiv(num(1), func("tanh", (type: "wild", name: "u"))),
    rhs: func("coth", (type: "wild", name: "u")),
    label: "1/tanh(u) = coth(u)",
    domain-sensitive: false,
  ),
  // Quotients
  (
    id: "quot-sin-cos",
    priority: 30,
    lhs: cdiv(func("sin", (type: "wild", name: "u")), func("cos", (type: "wild", name: "u"))),
    rhs: func("tan", (type: "wild", name: "u")),
    label: "sin(u)/cos(u) = tan(u)",
    domain-sensitive: false,
  ),
  (
    id: "quot-cos-sin",
    priority: 31,
    lhs: cdiv(func("cos", (type: "wild", name: "u")), func("sin", (type: "wild", name: "u"))),
    rhs: func("cot", (type: "wild", name: "u")),
    label: "cos(u)/sin(u) = cot(u)",
    domain-sensitive: false,
  ),
  (
    id: "quot-sinh-cosh",
    priority: 32,
    lhs: cdiv(func("sinh", (type: "wild", name: "u")), func("cosh", (type: "wild", name: "u"))),
    rhs: func("tanh", (type: "wild", name: "u")),
    label: "sinh(u)/cosh(u) = tanh(u)",
    domain-sensitive: false,
  ),
  (
    id: "quot-cosh-sinh",
    priority: 33,
    lhs: cdiv(func("cosh", (type: "wild", name: "u")), func("sinh", (type: "wild", name: "u"))),
    rhs: func("coth", (type: "wild", name: "u")),
    label: "cosh(u)/sinh(u) = coth(u)",
    domain-sensitive: false,
  ),
  // Inverse/function cancellation
  (
    id: "sin-arcsin",
    priority: 40,
    lhs: func("sin", func("arcsin", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sin(arcsin(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "cos-arccos",
    priority: 41,
    lhs: func("cos", func("arccos", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "cos(arccos(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "tan-arctan",
    priority: 42,
    lhs: func("tan", func("arctan", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "tan(arctan(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "csc-arccsc",
    priority: 43,
    lhs: func("csc", func("arccsc", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "csc(arccsc(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "sec-arcsec",
    priority: 44,
    lhs: func("sec", func("arcsec", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sec(arcsec(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "cot-arccot",
    priority: 45,
    lhs: func("cot", func("arccot", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "cot(arccot(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "sinh-arcsinh",
    priority: 46,
    lhs: func("sinh", func("arcsinh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sinh(arcsinh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "cosh-arccosh",
    priority: 47,
    lhs: func("cosh", func("arccosh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "cosh(arccosh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "tanh-arctanh",
    priority: 48,
    lhs: func("tanh", func("arctanh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "tanh(arctanh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "csch-arccsch",
    priority: 49,
    lhs: func("csch", func("arccsch", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "csch(arccsch(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "sech-arcsech",
    priority: 50,
    lhs: func("sech", func("arcsech", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sech(arcsech(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "coth-arccoth",
    priority: 51,
    lhs: func("coth", func("arccoth", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "coth(arccoth(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arcsin-sin",
    priority: 52,
    lhs: func("arcsin", func("sin", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arcsin(sin(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arccos-cos",
    priority: 53,
    lhs: func("arccos", func("cos", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccos(cos(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arctan-tan",
    priority: 54,
    lhs: func("arctan", func("tan", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arctan(tan(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arccsc-csc",
    priority: 55,
    lhs: func("arccsc", func("csc", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccsc(csc(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arcsec-sec",
    priority: 56,
    lhs: func("arcsec", func("sec", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arcsec(sec(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arccot-cot",
    priority: 57,
    lhs: func("arccot", func("cot", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccot(cot(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arcsinh-sinh",
    priority: 58,
    lhs: func("arcsinh", func("sinh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arcsinh(sinh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arccosh-cosh",
    priority: 59,
    lhs: func("arccosh", func("cosh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccosh(cosh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arctanh-tanh",
    priority: 60,
    lhs: func("arctanh", func("tanh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arctanh(tanh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arccsch-csch",
    priority: 61,
    lhs: func("arccsch", func("csch", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccsch(csch(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arcsech-sech",
    priority: 62,
    lhs: func("arcsech", func("sech", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arcsech(sech(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arccoth-coth",
    priority: 63,
    lhs: func("arccoth", func("coth", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccoth(coth(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "exp-ln",
    priority: 64,
    lhs: func("exp", func("ln", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "exp(ln(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "ln-exp",
    priority: 65,
    lhs: func("ln", func("exp", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "ln(exp(u)) = u",
    domain-sensitive: false,
  ),
  // Log structural rewrites (kept for compatibility; domain-sensitive metadata only).
  (
    id: "ln-mul",
    priority: 70,
    lhs: func("ln", mul((type: "wild", name: "a"), (type: "wild", name: "b"))),
    rhs: add(func("ln", (type: "wild", name: "a")), func("ln", (type: "wild", name: "b"))),
    label: "ln(a·b) = ln(a) + ln(b)",
    domain-sensitive: true,
  ),
  (
    id: "ln-div",
    priority: 71,
    lhs: func("ln", cdiv((type: "wild", name: "a"), (type: "wild", name: "b"))),
    rhs: sub(func("ln", (type: "wild", name: "a")), func("ln", (type: "wild", name: "b"))),
    label: "ln(a/b) = ln(a) - ln(b)",
    domain-sensitive: true,
  ),
  (
    id: "ln-pow",
    priority: 72,
    lhs: func("ln", pow((type: "wild", name: "a"), (type: "wild", name: "n"))),
    rhs: mul((type: "wild", name: "n"), func("ln", (type: "wild", name: "a"))),
    label: "ln(a^n) = n·ln(a)",
    domain-sensitive: true,
  ),
)
